---
# Ansible playbook for a LEMP server.
#
# @author Jeff Geerling (2014).

- hosts: all
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.nginx
    - geerlingguy.php
    - geerlingguy.adminer
    - geerlingguy.git
    - git_deployer
    - geerlingguy.mysql
    - geerlingguy.php-mysql
    - debops.postfix
    - ansible_role_git_deployer
