---
# Ansible playbook for a LEMP server.
#
# @author Jeff Geerling (2014).

- hosts: all
  gather_facts: yes

  vars_files:
    - {ANSIBLE_VARS}

  roles:
    - geerlingguy.firewall
    - geerlingguy.nginx
    - geerlingguy.php
    - geerlingguy.adminer
    - geerlingguy.git
    - debops.postgresql
    - geerlingguy.php-pgsql
    - debops.postfix
    - ansible_role_git_deployer
