---
- hosts: all
  gather_facts: yes
  become: True

  vars_files:
    - {ANSIBLE_VARS}

  roles:
    - ansible_role_nginx
    - ansible_role_php
    - ansible_role_git
    - ansible_role_postgres
    - ansible_role_adminer
    - ansible_role_postfix
    - ansible_role_composer
    